# Generated by Django 5.2.4 on 2025-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_options_alter_blog_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
